# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Jan 11 18:00:57 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(230, 230)
        MainWindow.setMinimumSize(QtCore.QSize(230, 230))
        MainWindow.setMaximumSize(QtCore.QSize(230, 230))
        MainWindow.setBaseSize(QtCore.QSize(10000, 10000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icono.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 101, 116))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 21, 72, 88))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.senoidal = QtGui.QRadioButton(self.layoutWidget)
        self.senoidal.setChecked(True)
        self.senoidal.setObjectName(_fromUtf8("senoidal"))
        self.verticalLayout.addWidget(self.senoidal)
        self.triangular = QtGui.QRadioButton(self.layoutWidget)
        self.triangular.setObjectName(_fromUtf8("triangular"))
        self.verticalLayout.addWidget(self.triangular)
        self.rampa = QtGui.QRadioButton(self.layoutWidget)
        self.rampa.setObjectName(_fromUtf8("rampa"))
        self.verticalLayout.addWidget(self.rampa)
        self.cuadrada = QtGui.QRadioButton(self.layoutWidget)
        self.cuadrada.setObjectName(_fromUtf8("cuadrada"))
        self.verticalLayout.addWidget(self.cuadrada)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 101, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.frecuencia = QtGui.QSpinBox(self.groupBox_2)
        self.frecuencia.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.frecuencia.setToolTip(_fromUtf8(""))
        self.frecuencia.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.frecuencia.setAccelerated(True)
        self.frecuencia.setMaximum(10000)
        self.frecuencia.setProperty("value", 5000)
        self.frecuencia.setObjectName(_fromUtf8("frecuencia"))
        self.generar = QtGui.QPushButton(self.centralwidget)
        self.generar.setGeometry(QtCore.QRect(120, 15, 101, 23))
        self.generar.setObjectName(_fromUtf8("generar"))
        self.pausar = QtGui.QPushButton(self.centralwidget)
        self.pausar.setGeometry(QtCore.QRect(120, 45, 101, 23))
        self.pausar.setObjectName(_fromUtf8("pausar"))
        self.borrar = QtGui.QPushButton(self.centralwidget)
        self.borrar.setGeometry(QtCore.QRect(120, 75, 101, 23))
        self.borrar.setObjectName(_fromUtf8("borrar"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 100, 101, 81))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.offset = QtGui.QSlider(self.groupBox_3)
        self.offset.setGeometry(QtCore.QRect(10, 20, 80, 20))
        self.offset.setMinimum(-100)
        self.offset.setMaximum(100)
        self.offset.setOrientation(QtCore.Qt.Horizontal)
        self.offset.setInvertedAppearance(True)
        self.offset.setTickPosition(QtGui.QSlider.TicksAbove)
        self.offset.setTickInterval(20)
        self.offset.setObjectName(_fromUtf8("offset"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 40, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 46, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lOffset = QtGui.QLabel(self.groupBox_3)
        self.lOffset.setGeometry(QtCore.QRect(60, 60, 36, 16))
        self.lOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lOffset.setObjectName(_fromUtf8("lOffset"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 15, 71, 166))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.amplitud = QtGui.QSlider(self.groupBox_4)
        self.amplitud.setGeometry(QtCore.QRect(10, 20, 20, 141))
        self.amplitud.setToolTip(_fromUtf8(""))
        self.amplitud.setMaximum(100)
        self.amplitud.setSliderPosition(50)
        self.amplitud.setOrientation(QtCore.Qt.Vertical)
        self.amplitud.setTickPosition(QtGui.QSlider.TicksBelow)
        self.amplitud.setObjectName(_fromUtf8("amplitud"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 34, 145))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 230, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setEnabled(True)
        self.menuEditar.setTearOffEnabled(False)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionConfiguracion = QtGui.QAction(MainWindow)
        self.actionConfiguracion.setEnabled(True)
        self.actionConfiguracion.setIconVisibleInMenu(True)
        self.actionConfiguracion.setObjectName(_fromUtf8("actionConfiguracion"))
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionConfiguracion)
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.senoidal, self.triangular)
        MainWindow.setTabOrder(self.triangular, self.rampa)
        MainWindow.setTabOrder(self.rampa, self.cuadrada)
        MainWindow.setTabOrder(self.cuadrada, self.frecuencia)
        MainWindow.setTabOrder(self.frecuencia, self.offset)
        MainWindow.setTabOrder(self.offset, self.amplitud)
        MainWindow.setTabOrder(self.amplitud, self.generar)
        MainWindow.setTabOrder(self.generar, self.pausar)
        MainWindow.setTabOrder(self.pausar, self.borrar)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "UTN - Señales", None))
        self.groupBox.setStatusTip(_translate("MainWindow", "Ajuste del tipo de señal", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tipo de señal", None))
        self.senoidal.setStatusTip(_translate("MainWindow", "Ajuste del tipo de señal (senoidal)", None))
        self.senoidal.setText(_translate("MainWindow", "Senoidal", None))
        self.triangular.setStatusTip(_translate("MainWindow", "Ajuste del tipo de señal (triangular)", None))
        self.triangular.setText(_translate("MainWindow", "Triangular", None))
        self.rampa.setStatusTip(_translate("MainWindow", "Ajuste del tipo de señal (rampa)", None))
        self.rampa.setText(_translate("MainWindow", "Rampa", None))
        self.cuadrada.setStatusTip(_translate("MainWindow", "Ajuste del tipo de señal (cuadrada)", None))
        self.cuadrada.setText(_translate("MainWindow", "Cuadrada", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Frecuencia", None))
        self.frecuencia.setStatusTip(_translate("MainWindow", "Ajuste de frecuencia de la señal", None))
        self.frecuencia.setSuffix(_translate("MainWindow", " Hz", None))
        self.generar.setStatusTip(_translate("MainWindow", "Inicia la señal configurada", None))
        self.generar.setText(_translate("MainWindow", "Generar", None))
        self.pausar.setStatusTip(_translate("MainWindow", "Pausa la señal generada", None))
        self.pausar.setText(_translate("MainWindow", "Pausar", None))
        self.borrar.setStatusTip(_translate("MainWindow", "Pausa y borra la señal configurada", None))
        self.borrar.setText(_translate("MainWindow", "Borrar", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Offset", None))
        self.offset.setToolTip(_translate("MainWindow", "0", None))
        self.offset.setStatusTip(_translate("MainWindow", "Ajusta el nivel de offset de la señal", None))
        self.label.setText(_translate("MainWindow", "-100%", None))
        self.label_2.setText(_translate("MainWindow", "+100%", None))
        self.label_14.setText(_translate("MainWindow", "Offset = ", None))
        self.lOffset.setText(_translate("MainWindow", "0 %", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Amplitud", None))
        self.amplitud.setStatusTip(_translate("MainWindow", "Ajusta la amplitud pico-pico", None))
        self.label_3.setText(_translate("MainWindow", "100 %", None))
        self.label_5.setText(_translate("MainWindow", "90 %", None))
        self.label_6.setText(_translate("MainWindow", "80%", None))
        self.label_7.setText(_translate("MainWindow", "70%", None))
        self.label_8.setText(_translate("MainWindow", "60%", None))
        self.label_9.setText(_translate("MainWindow", "50%", None))
        self.label_10.setText(_translate("MainWindow", "40%", None))
        self.label_11.setText(_translate("MainWindow", "30%", None))
        self.label_12.setText(_translate("MainWindow", "20%", None))
        self.label_13.setText(_translate("MainWindow", "10%", None))
        self.label_4.setText(_translate("MainWindow", "0%", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar", None))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda", None))
        self.actionSalir.setText(_translate("MainWindow", "Salir", None))
        self.actionSalir.setStatusTip(_translate("MainWindow", "Salir de la aplicación", None))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionConfiguracion.setText(_translate("MainWindow", "Configuracion", None))
        self.actionConfiguracion.setStatusTip(_translate("MainWindow", "Configuración del generador", None))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de...", None))

